<a href="https://colab.research.google.com/github/kay-squared/PyTorchLearn/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Ask questions in: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


## Introduction to tensors

### Creating tensors

https://pytorch.org/docs/stable/tensors.html

In [81]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [82]:
scalar.ndim
scalar.item()   # get tensor back as python int

7

In [83]:
#vector
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [84]:
#MATRIX
MATRIX = torch.tensor([[7,7],[8,9]])
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

2
torch.Size([2, 2])
tensor([8, 9])


In [85]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [86]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR)

3
torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [87]:
TENSOR[0]   # there is 1 3by3 thing which has index 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
TENSOR[0][0]

tensor([1, 2, 3])

In [89]:
TENSOR[0][2]

tensor([7, 8, 9])

In [90]:
TENSOR[0][1][1]

tensor(5)

## Random tensors

Random tensors are important because the way many NN learn is that they are initialized with random tensors.

https://pytorch.org/docs/stable/generated/torch.rand.html

In [91]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [92]:
random_tensor.ndim

2

In [93]:
random_tensor = torch.rand(2,3,4)
random_tensor
random_tensor.ndim

3

In [94]:
# create a random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

## Tensor with zeros and ones

In [95]:
# Create a tensor of all zeros
# for masking out numbers

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [96]:
ones = torch.ones(size=(3,4))
ones
ones.dtype

torch.float32

## Creating a range of tensors and tensors_like

In [97]:
# arange
one_to_ten=torch.arange(1,1000,77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [98]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
# like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

types:
* None (--> float 32)
* float16
* floate64
* ...


https://pytorch.org/docs/stable/tensors.html


Dataypes give rise to one of the most common errors, the other ones being related to device adn to shape>

1. Tensors dont have correct datatype
2. tensors dont have the correct shape
3. tensors are not on the right device (if tensors have to interact, they should live on the same device

In [100]:
float_32_tensor=torch.tensor([3,6,8])
float_32_tensor.type

<function Tensor.type>

In [101]:
float_16_tensor=torch.tensor([3,6,8],
                             dtype=torch.float16,    # datatype of the tensor
                             device=None,           # "cpu", "cuda"
                             requires_grad=False  # whether or not I want torch to keep track of gradients with tensor operations
                             )

In [102]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 8.], dtype=torch.float16)

In [103]:
# against expections, this does not result in an error, there is some background going on here, 
float_16_tensor * float_32_tensor


tensor([ 9., 36., 64.], dtype=torch.float16)

In [104]:
int_32_tensor =torch.tensor([3,6,9],dtype=torch.int32)

In [105]:

float_16_tensor * int_32_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

Apparently we did not succeed in getting an error

## Getting information from tensors:

1. Tensors dont have correct datatype: tensor.dtype
2. tensors dont have the correct shape: tensor.shape
3. tensors are not on the right device (if tensors have to interact, they should live on the same device : tensor.device

In [106]:
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.4436, 0.9726, 0.5194, 0.5337],
        [0.7050, 0.3362, 0.7891, 0.1694],
        [0.1800, 0.7177, 0.6988, 0.5510]])

In [107]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}|")
print(f"Size of tensor: {some_tensor.size()}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")




tensor([[0.4436, 0.9726, 0.5194, 0.5337],
        [0.7050, 0.3362, 0.7891, 0.1694],
        [0.1800, 0.7177, 0.6988, 0.5510]])
Datatype of tensor: torch.float32|
Size of tensor: torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating tensors (tensor operation)

* addition
* subtraction
* multiplication
* divison
* matrix multiplication



### Using python operators

In [108]:
#addition

tensor = torch.tensor([1,2,3])
tensor+=10
tensor

tensor([11, 12, 13])

In [109]:
tensor+torch.ones_like(tensor)

tensor([12, 13, 14])

In [110]:
# multiplication
tensor*=10
tensor

tensor([110, 120, 130])

In [111]:
# subtract

tensor-=6
tensor

tensor([104, 114, 124])

### pytorch inbuilt functions

In [112]:
torch.mul(tensor,14)
torch.add(tensor,-1000)


tensor([-896, -886, -876])

### Matrix Multiplication

1. Elementwise
2. Matmult

#### Element wise multiplication

In [113]:
torch.tensor([1,2,3])*torch.tensor([1,2,3])

tensor([1, 4, 9])

#### Matrix multiplication

In [114]:
# dot product
tensor = torch.tensor([1,2,3])
torch.matmul(tensor,tensor)

tensor(14)

In [115]:
# time issue
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.68 ms, sys: 188 µs, total: 1.87 ms
Wall time: 2.15 ms


In [116]:
%%time
torch.matmul(tensor,tensor)       # this is much faster!

CPU times: user 32 µs, sys: 9 µs, total: 41 µs
Wall time: 44.8 µs


tensor(14)

In [117]:
tensor@tensor

tensor(14)

### One of the most common errors in deep learning:  Shape errors!

There are two main rules for matrix multiplications:
1. the inner dimensions must match: (3,2) @ (2,3)
2. the resultign matrix has the shape of the outer dimensions

In [118]:
# will not work
# torch.matmul(torch.rand(3,2),torch.rand(3,2))

In [119]:
# will work
torch.matmul(torch.rand(3,2),torch.rand(2,3))
#torch.mm is an alias for matmul

tensor([[0.4275, 0.5550, 0.6655],
        [0.1185, 0.1079, 0.1145],
        [0.3934, 0.4346, 0.4964]])

In [120]:
tensor_A = torch.tensor([[1,2],[2,3],[3,4]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### Transpose

In [121]:
print(torch.mm(tensor_A,tensor_B.T))

print(torch.mm(tensor_A,tensor_B.T).size())


tensor([[23, 29, 35],
        [38, 48, 58],
        [53, 67, 81]])
torch.Size([3, 3])


## Tensor Aggregation

* mean
* max, min
* sum
* ...

In [122]:
x = torch.arange(0,100,10)
print(x,x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64


In [123]:
print(torch.min(x))
x.min()
x.max()
torch.sum(x), x.sum()

tensor(0)


(tensor(450), tensor(450))

In [124]:
# torch.mean and x.mean() do not work on data type long!!!
# will not work:
#torch.mean(x)

print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())


tensor(45.)
tensor(45.)


## Argmax and argmin (positional max and min)

In [125]:
x,x.argmin(), x.argmax()


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0), tensor(9))

## Reshaping, squeezing, unsqueezing

* torch.reshape: reshpae an input tensor to defined shape (the number of elements has to stay the same!)
* torch.view: return a view of an input tensor of certain shape but keep the same memory as the origional tensor
* torch.stack, torch.vstack, torch.hstack: combine multiple tensors on top of eacxh other (vertical) or side by side (h stack)
* torch.squeeze: removes of 1-dimensions from a tensor
* torch.unsqueeze: add a 1 dimension
* torch.permute: returns a view with dimensions permuted




In [126]:

x = torch.arange(1.,11.)
x,x.shape


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [127]:
# add an extra dimension
# the shape has to be in accordance with the original dimensions
# will not work
#x_reshaped = x.reshape(1,7)
# will work:
x_reshaped = x.reshape(1,10)
x.shape,x,x_reshaped, x_reshaped.shape

(torch.Size([10]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [128]:
# both ways work
x_reshaped = x.reshape(10,1)
x.shape,x_reshaped, x_reshaped.shape

(torch.Size([10]), tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]), torch.Size([10, 1]))

In [129]:

x.reshape(2,5),x.reshape(5,2) 

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]), tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [130]:
# changing the view:
# note that changing z changes x also, as typical in pythons
z=x.view(1,10)
print(x)
z[:,0]=20
print(x)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [131]:
# Stacking tensors on top of each other
# dim =0 is the default = vstack
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape



(tensor([[20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [132]:
x_stacked = torch.stack([x,x,x,x], dim=1)   # = hstack
x_stacked, x_stacked.shape


(tensor([[20., 20., 20., 20.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]), torch.Size([10, 4]))

In [133]:
# Squeeze and unsqueeze

x = torch.zeros(2,1,2,1,2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x,0)
print(y.size())
y = torch.squeeze(x,1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [134]:

x = torch.arange(1.,11.)
print(x,x.shape)
x_reshaped = x.reshape(1,10)
print(x_reshaped,x_reshaped.shape)
print(x_reshaped.squeeze(),x_reshaped.squeeze().shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])


In [135]:
x_unsqueezed=torch.unsqueeze(x,dim=0)   #  gives one line
x,x.shape, x_unsqueezed,x_unsqueezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [136]:
x_unsqueezed=torch.unsqueeze(x,dim=1)     # gives one column
x,x.shape, x_unsqueezed,x_unsqueezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [137]:
# Permute
# gives a view with permuted dimensions

x = torch.rand(2,3,5)
print(f"shape of original x {x.shape}")
x_permuted = torch.permute(x,(2,0,1))
print(f"shape of permuted x {x_permuted.shape}")

shape of original x torch.Size([2, 3, 5])
shape of permuted x torch.Size([5, 2, 3])


In [138]:
# with images:

x_original = torch.rand(size=(224,224,3))
x_permuted = torch.permute(x_original,(2,0,1))
print(x_original.shape,x_permuted.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])


In [139]:
# not that it is a view
# the element that is changed in one of the tensors will change in the other one
# pay attention to the different indices in the permuted tensor!

print(x_original[0][1][2],x_permuted[2][0][1])
x_original[0][1][2] = 33
x_original[0][1][2],x_permuted[2][0][1]



tensor(0.4626) tensor(0.4626)


(tensor(33.), tensor(33.))

## Indexing

similar to indexing with numpy

In [140]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [141]:
x[0]    # index on the first dimension (size 1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [142]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [143]:
x[0][2][2],x[0,2,2]

(tensor(9), tensor(9))

In [144]:
3 # use colon to select all of the target dimension



3

In [145]:
x[:,0]

tensor([[1, 2, 3]])

In [146]:
x[:,:,0], x[:,0:2,0],x[:,:2,0]

(tensor([[1, 4, 7]]), tensor([[1, 4]]), tensor([[1, 4]]))

In [147]:
print(x[:,1,1])
print(x[0,1,1])

tensor([5])
tensor(5)


In [148]:
# return 9
x[0,2,2]

tensor(9)

In [149]:
# return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensor and numpy

About interactions between Pytorch and numpy
* e.g. data in mumpy, want it in tensor: torch.from_numpy (takes an np array and changes it to a tensor)
* from tensor to numpy: torch.Tensor.numpy()

In [150]:
# numpy array to tensor
array = np.arange(1,8)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype    # the default dtype in numpy is float64 but not pytorches!


(dtype('int64'), torch.int64)

In [151]:
tensor = torch.from_numpy(array).type(torch.float32)

In [152]:
# check out what happens if we change a value in the array --> does not change tensor
print(array[3],tensor[3])
array[3]=10
print(array[3],tensor[3])

4 tensor(4.)
10 tensor(4.)


In [153]:
# tensor to mumpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()     # againm the numpy array gets the data type of the tensor.
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [154]:
# change the tensor - the array element DOES change!!
print(tensor[3],numpy_tensor[3])
tensor[3]=10
print(tensor[3],numpy_tensor[3])

tensor(1.) 1.0
tensor(10.) 10.0


## PyTorch Reproducability
trying to take the random out of the random!

NN: start with random numbers - perform tensor operation - update random numbers - ....

Sometimes we want to take out a bit of the randomness


https://pytorch.org/docs/stable/notes/randomness.html

https://en.wikipedia.org/wiki/Random_seed

In [155]:
# randomness
[print(torch.rand(3)) for i in np.arange(10)]

tensor([0.0439, 0.4367, 0.4731])
tensor([0.9129, 0.0017, 0.1279])
tensor([0.2028, 0.6808, 0.9808])
tensor([0.8409, 0.7430, 0.3531])
tensor([0.0833, 0.1122, 0.4030])
tensor([0.3140, 0.8325, 0.2196])
tensor([0.6822, 0.8682, 0.9207])
tensor([0.7991, 0.6096, 0.6553])
tensor([0.5985, 0.7002, 0.7376])
tensor([0.2238, 0.2798, 0.9330])


[None, None, None, None, None, None, None, None, None, None]

In [156]:
# without random seed
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A, random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7582, 0.0692, 0.2671, 0.7370],
        [0.5789, 0.2300, 0.8886, 0.5439],
        [0.7183, 0.2034, 0.3077, 0.7451]]) tensor([[0.2455, 0.1387, 0.0803, 0.0832],
        [0.7169, 0.7576, 0.3273, 0.7462],
        [0.7254, 0.8974, 0.2768, 0.6498]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [157]:
# reduce randomness with a seed: flavour the randomness (e.g. for sharing with someone else)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

# have to set it everytime!
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A, random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pyTorch objects on GPUs

for faster computation on numbers, thanks to CUDA = NVIDIA + Pytorch behind the scenes

### Gettiing a GPU
* use colab (also Pro,m Pro +)
* Use your own GPU (investiment, setup): https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
* use cloud computing such as GCP (google cloud), AWS, Azure = renting and accessing computers on cloud (also takes a little bit of setting up)

PyTorch Setting up Documentation!


In [159]:
# Check for GPU
print(torch.cuda.is_available())
# count GPUs
print(torch.cuda.device_count())



True
1


## Device agnostic code

https://pytorch.org/docs/stable/notes/cuda.html?highlight=cuda+semantics

Its best practice to set up device agnostic code as pytorch runs on both gpu and cpu. ue gpu if available otherwise default to cpu





In [160]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


## Device agnostic objects

Putting tensors and models on the GPU




In [161]:
# default tensor i on cpu
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [163]:
# move tensor to gpu if available
device="cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)    # used a lot, also for models!
tensor_on_gpu2 = tensor.cuda()

print(tensor_on_gpu, tensor_on_gpu.device)
print(tensor_on_gpu2, tensor_on_gpu2.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3], device='cuda:0') cuda:0


In [168]:
# moving tensors vback to cpu (tenor ono gpu, cant transform to numpy?)
# this will not work
#tensor_on_gpu.numpy()

tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy()

print(tensor_on_gpu, tensor_on_gpu.device)
print(tensor_on_cpu, tensor_on_cpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3]) cpu


# Exercises !!

found here, on the bottom of the page: https://www.learnpytorch.io/00_pytorch_fundamentals/

1. Create a random tensor with shape (7, 7).
2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
3. Set the random seed to 0 and do exercises 2 & 3 over again.
4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
7. Find the maximum and minimum values of the output of 7.
8. Find the maximum and minimum index values of the output of 7.
9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


Link to Exercises:
https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras/exercises

(open notebook via github!)

In [173]:
# 1. Create a random tensor with shape (7, 7)
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008, 0.9302],
        [0.6558, 0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947, 0.0897, 0.8712, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037, 0.9555, 0.1035, 0.6258, 0.2849],
        [0.4452, 0.1258, 0.9554, 0.1330, 0.7672, 0.6757, 0.6625],
        [0.2297, 0.9545, 0.6099, 0.5643, 0.0594, 0.7099, 0.4250],
        [0.2709, 0.9295, 0.6115, 0.2234, 0.2469, 0.4761, 0.7792]])

In [174]:
# 2. Perform a matrix multiplication on the tensor from 1 
# with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

tensor2 = torch.rand(1,7)
tensor3 = torch.mm(tensor1, tensor2.T)
tensor3

tensor([[1.2308],
        [0.8691],
        [1.2840],
        [1.4394],
        [1.6629],
        [1.2447],
        [1.1423]])

In [176]:
# 3 Set the random seed to 0 and do exercises 1 & 2 over again

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(7,7)
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)
tensor3 = torch.mm(tensor1, tensor2.T)
tensor3

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [207]:
# 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one).
#  If there is, set the GPU random seed to 1234.

RANDOM_SEED = 1234


tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
tensor3 = torch.mm(tensor1,tensor2.T)
print(tensor3)

torch.cuda.manual_seed(RANDOM_SEED)
tensor4 = torch.rand(7,7).cuda()
torch.cuda.manual_seed(RANDOM_SEED)
tensor5 = torch.rand(1,7).cuda()
tensor6 = torch.mm(tensor4,tensor5.T).cuda()
print(tensor6)

tensor([[1.2655],
        [0.8688],
        [0.7714],
        [1.0739],
        [0.9436],
        [1.6868],
        [1.2337]])
tensor([[2.2280],
        [1.7299],
        [2.0192],
        [1.8660],
        [1.8862],
        [2.4169],
        [1.3882]], device='cuda:0')


In [196]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

tensor7 = torch.rand(2,3).cuda()
tensor8 = torch.rand(2,3).cuda()
torch.manual_seed(1234)

In [199]:
# 6. Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors)

tensor9 = torch.mm(tensor7, tensor8.T)
tensor9

tensor([[1.0783, 0.5126],
        [0.4909, 0.2226]], device='cuda:0')

In [205]:
# 7. Find the maximum and minimum values of the output of 7.
# 8. Find the maximum and minimum index values of the output of 7.

print(torch.min(tensor9))
print(torch.max(tensor9))
print(torch.argmin(tensor9))
print(torch.argmax(tensor9))

tensor(0.2226, device='cuda:0')
tensor(1.0783, device='cuda:0')
tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


In [210]:
# Make a random tensor with shape (1, 1, 1, 10) 
# and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
tensor10=torch.rand(1,1,1,10)
tensor11=tensor10.squeeze()
print(tensor10,tensor10.shape)
print(tensor11,tensor11.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [ ]:
a
